// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egappgscndgwhwltjoed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnYXBwZ3NjbmRnd2h3bHRqb2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTA2MjYsImV4cCI6MjA2ODQ4NjYyNn0.RRot7LTUevvW53yo0P-e8TS75I__4sS7iXf0_-U7Bkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});